# Generated by Django 4.1.4 on 2022-12-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_autos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
            ],
        ),
    ]
