# Generated by Django 4.1.4 on 2023-01-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argentina', '0004_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sub_titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(max_length=3000)),
            ],
        ),
    ]
